"""PDF audit report generation with fpdf2.

Produces a regulator-ready audit document for a single call or a batch summary.

Unicode handling: transcripts are transliterated Hinglish (latin letters), but
LLM output and our formatting can include curly quotes, en-dashes, and the
occasional non-latin glyph. If a Unicode TTF (DejaVuSans) is available we embed
it; otherwise we sanitise text to a latin-1-safe form so generation never crashes.
"""

from __future__ import annotations

from pathlib import Path

from fpdf import FPDF

from .models import CallComplianceReport, ComplianceStatus, Severity

# Optional embedded font for full Unicode. Drop a DejaVuSans.ttf here to enable.
_FONT_PATH = Path(__file__).resolve().parent.parent / "assets" / "fonts" / "DejaVuSans.ttf"

# Palette (RGB) mirrored from the Craft AI theme.
_INK = (43, 38, 34)
_BRICK = (198, 72, 43)
_SAND = (154, 123, 46)
_SAGE = (79, 122, 82)
_MUTED = (107, 98, 89)

_STATUS_COLOR = {
    ComplianceStatus.COMPLIANT: _SAGE,
    ComplianceStatus.REVIEW: _SAND,
    ComplianceStatus.NON_COMPLIANT: _BRICK,
}
_SEVERITY_COLOR = {
    Severity.CRITICAL: _BRICK,
    Severity.WARNING: _SAND,
    Severity.INFO: _MUTED,
}

# Characters fpdf2 core fonts (latin-1) cannot render -> safe replacements.
_REPLACEMENTS = {
    "\u2018": "'", "\u2019": "'", "\u201c": '"', "\u201d": '"',
    "\u2013": "-", "\u2014": "-", "\u2026": "...", "\u2022": "-",
    "\u20b9": "Rs.", "\u00a0": " ",
}


class _AuditPDF(FPDF):
    unicode = False

    def header(self) -> None:
        self.set_fill_color(*_BRICK)
        self.rect(0, 0, self.w, 18, style="F")
        self.set_xy(12, 5)
        self.set_text_color(255, 255, 255)
        self._font("B", 13)
        self.cell(0, 8, self._s("RBI Compliance Audit Report"))
        self.set_xy(12, 22)
        self.set_text_color(*_MUTED)
        self._font("", 8)
        self.cell(
            0, 5,
            self._s(
                "Generated by RBI Compliance & Call Quality Inspector · "
                "clause references are configurable — verify against official RBI text"
            ),
        )
        self.ln(10)

    def footer(self) -> None:
        self.set_y(-12)
        self.set_text_color(*_MUTED)
        self._font("", 7)
        self.cell(0, 6, self._s(f"Page {self.page_no()}"), align="C")

    # --- font + text helpers -------------------------------------------------
    def _font(self, style: str = "", size: int = 10) -> None:
        family = "DejaVu" if self.unicode else "Helvetica"
        self.set_font(family, style, size)

    def _s(self, text: str) -> str:
        if self.unicode:
            return text
        for bad, good in _REPLACEMENTS.items():
            text = text.replace(bad, good)
        return text.encode("latin-1", "replace").decode("latin-1")


def _new_pdf() -> _AuditPDF:
    pdf = _AuditPDF()
    pdf.set_auto_page_break(auto=True, margin=16)
    if _FONT_PATH.exists():
        # add_font is safe to call per-instance; fpdf2 registers fonts on the
        # instance. Wrapped defensively so a font issue never breaks export.
        try:
            pdf.add_font("DejaVu", "", str(_FONT_PATH))
            pdf.add_font("DejaVu", "B", str(_FONT_PATH))
            pdf.unicode = True
        except Exception:  # noqa: BLE001 - fall back to sanitised latin-1
            pdf.unicode = False
    return pdf


def _kv_row(pdf: _AuditPDF, label: str, value: str) -> None:
    pdf.set_text_color(*_MUTED)
    pdf._font("", 9)
    pdf.cell(48, 6, pdf._s(label))
    pdf.set_text_color(*_INK)
    pdf._font("B", 9)
    pdf.cell(0, 6, pdf._s(value), new_x="LMARGIN", new_y="NEXT")


def _render_report(pdf: _AuditPDF, report: CallComplianceReport) -> None:
    # Status banner
    color = _STATUS_COLOR[report.compliance_status]
    pdf.set_fill_color(*color)
    pdf.set_text_color(255, 255, 255)
    pdf._font("B", 11)
    pdf.cell(
        0, 9,
        pdf._s(f"  {report.call_id}   —   {report.compliance_status.value}   "
               f"(risk {report.overall_risk_score}/100)"),
        new_x="LMARGIN", new_y="NEXT", fill=True,
    )
    pdf.ln(3)

    _kv_row(pdf, "Agent", report.agent_id)
    _kv_row(pdf, "Customer", report.customer_id)
    if report.timestamp:
        _kv_row(pdf, "Call timestamp", report.timestamp.strftime("%Y-%m-%d %H:%M"))
    _kv_row(pdf, "Calls today", str(report.call_count_today))
    _kv_row(pdf, "Within permitted hours", "Yes" if report.time_of_day_compliant else "No")
    _kv_row(pdf, "Consent disclosed", "Yes" if report.consent_given else "No")
    pdf.ln(3)

    # Violations
    pdf.set_text_color(*_INK)
    pdf._font("B", 11)
    pdf.cell(0, 7, pdf._s(f"Violations ({len(report.violations)})"),
             new_x="LMARGIN", new_y="NEXT")
    if not report.violations:
        pdf.set_text_color(*_SAGE)
        pdf._font("", 9)
        pdf.cell(0, 6, pdf._s("No violations detected — call is compliant."),
                 new_x="LMARGIN", new_y="NEXT")
    for v in report.violations:
        sev_color = _SEVERITY_COLOR[v.severity]
        pdf.ln(1)
        pdf.set_text_color(*sev_color)
        pdf._font("B", 9)
        pdf.cell(0, 6, pdf._s(f"[{v.severity.value}] {v.type}  ({v.source.value})"),
                 new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(*_INK)
        pdf._font("", 9)
        pdf.multi_cell(0, 5, pdf._s(f'"{v.quote}"'))
        pdf.set_text_color(*_MUTED)
        pdf._font("", 8)
        conf = f" · confidence {v.confidence:.2f}" if v.confidence is not None else ""
        pdf.cell(0, 5, pdf._s(f"@ {v.timestamp_offset}{conf}"),
                 new_x="LMARGIN", new_y="NEXT")
        pdf.multi_cell(0, 5, pdf._s(f"Ref: {v.rbi_clause}"))

    # Coaching summary
    if report.agent_coaching_summary:
        pdf.ln(3)
        pdf.set_text_color(*_INK)
        pdf._font("B", 11)
        pdf.cell(0, 7, pdf._s("Agent coaching summary"),
                 new_x="LMARGIN", new_y="NEXT")
        pdf._font("", 9)
        pdf.multi_cell(0, 5, pdf._s(report.agent_coaching_summary))


def build_call_pdf(report: CallComplianceReport) -> bytes:
    """Return PDF bytes for a single call audit report."""
    pdf = _new_pdf()
    pdf.add_page()
    _render_report(pdf, report)
    return bytes(pdf.output())


def build_batch_pdf(reports: list[CallComplianceReport]) -> bytes:
    """Return PDF bytes: a portfolio summary page then one page per call."""
    pdf = _new_pdf()
    pdf.add_page()

    total = len(reports)
    compliant = sum(1 for r in reports if r.compliance_status is ComplianceStatus.COMPLIANT)
    non_compliant = sum(
        1 for r in reports if r.compliance_status is ComplianceStatus.NON_COMPLIANT
    )
    rate = round(100 * compliant / total) if total else 0

    pdf.set_text_color(*_INK)
    pdf._font("B", 14)
    pdf.cell(0, 9, pdf._s("Portfolio Compliance Summary"),
             new_x="LMARGIN", new_y="NEXT")
    pdf.ln(2)
    _kv_row(pdf, "Calls audited", str(total))
    _kv_row(pdf, "Compliance rate", f"{rate}%")
    _kv_row(pdf, "Non-compliant calls", str(non_compliant))
    pdf.ln(4)

    pdf._font("B", 10)
    pdf.cell(60, 7, pdf._s("Call"))
    pdf.cell(40, 7, pdf._s("Agent"))
    pdf.cell(45, 7, pdf._s("Status"))
    pdf.cell(0, 7, pdf._s("Risk"), new_x="LMARGIN", new_y="NEXT")
    pdf._font("", 9)
    for r in reports:
        pdf.set_text_color(*_STATUS_COLOR[r.compliance_status])
        pdf.cell(60, 6, pdf._s(r.call_id))
        pdf.set_text_color(*_INK)
        pdf.cell(40, 6, pdf._s(r.agent_id))
        pdf.set_text_color(*_STATUS_COLOR[r.compliance_status])
        pdf.cell(45, 6, pdf._s(r.compliance_status.value))
        pdf.set_text_color(*_INK)
        pdf.cell(0, 6, pdf._s(str(r.overall_risk_score)),
                 new_x="LMARGIN", new_y="NEXT")

    for r in reports:
        pdf.add_page()
        _render_report(pdf, r)

    return bytes(pdf.output())
